# sinker, 38 degree arm slot, 92 mph

launch:
  handedness:    right
  arm_slot:      "38 degree"

  position:
    height: "6 ft 2 in"
    rubber: ["0 m", "18.44 m"]

  speed:       "97 mph"
  spin:        "2100 rpm"
  spin_axis:   [-1, 0, 0]
  clock_angle: "-30 degree"

  velocity:
    target: ["0.3 m", "0 m", "1.4 m"]
