# Yoshinobu Yamamoto (R) to William Contreras (R), 2026-05-24, p. 38
# https://baseballsavant.mlb.com/sporty-videos?playId=5e6ed387-6f11-3c61-8c3e-b00aefb7427e
# Slider, down and away, 85.4 mph
# Swinging strike

launch:
  handedness: right
  arm_slot: 44.0 degree
  position:
    height: 5 ft 10 in
    release_pos:
    - -1.84 ft
    - 53.82 ft
    - 5.49 ft
  speed: 85.4 mph
  spin: 2841.0 rpm
  spin_axis:
  - -1
  - 0
  - 0
  clock_angle: 130.0000 degree
  velocity:
    vector:
    - 5.308145555334036 ft/s
    - -124.26688005105726 ft/s
    - -4.167330265040512 ft/s